### ISSUE TITLE
Feature request: Wildcards, multiple addresses

### ISSUE THREAD

**Issue by idleberg** [corbosman/message_highlight#5]
glad this plugin exists, though i could think of several ways to make it more powerful
1. wildcards, obviously. maybe a regex option for the pros
2. option to apply a color to several addresses (comma-delimited list)

**Comment by JimyKK** [comment]
So I wanted something similar and modified this:
`if(stristr($message->$p['header'], $p['input'])) {`
to this:
`if(stripos($message->$p['header'], $p['input']) !== false) {`

This lets me match addresses that **contain** part of the text. Not exactly a wildcard but it's a start.
[Link to line in github repo](https://github.com/corbosman/message_highlight/blob/master/message_highlight.php#L58)

**Comment by corbosman** [comment]
It's not hard to use preg_match, but im a bit concerned about the performance. preg_match is considerably slower than strstr or strpos. 

strpos and strstr do pretty much the same in this context, so I dont see how changing to strpos would change anything.  stripos is a bit faster, so i dont mind changing it to that.

**Comment by JimyKK** [comment]
Ah OK, I'm brand new to php and was under the mistaken impression stripos allowed less strict string matching.

**Comment by MightyDrakeC** [comment]
Here's my multiple-address enhancement request.  It basically turns the plugin upside down, so it might require an entirely new plugin.

What I would like to see is, I choose a color, and then I choose the criteria that I would like to use to trigger that color.

For example:  My sports mailing lists.  Unfortunately, few of the teams ever use an actual mailing list system.  So, there's no consistent subject tag I can highlight on.  I have to test against an email address.  In fact, I usually end up with two or three addresses for each list.  Since I have to duplicate that for To: From: and CC: that ends up being nine or more entries for each one.  And, consistently picking the color from the fancy color picker is just about impossible.  I end up Copy&Pasting the color code from one to the next.  And it takes careful maneuvering of the mouse to not accidentally moving across the color picker patch.

So, what I would like to see is, I make my color choice.  I type in an arbitrary number of email addresses to test against.  There are checkboxes beside each address for which fields to match those against (default to all checked.  I have yet to come up with an example where I didn't duplicate each email address three times.)  And, an arbitrary number of subject tags to match against.  Then, on to the next color.

This would make it much easier to have a consistent color for each set of messages which belong together.

If not that, one teeny change that would make it much, much easier to copy colors from one to the next would be if you were to display the color code next to the color box, so that I can more easily highlight it when I need to add a new email address.  (People joining and leaving the teams, etc.)  What just popped to mind that I'm going to do with this new install of Roundcube is I'm going to create a bogus subject entry that holds the color code, so I don't have to remember it months from now.  That'll work, but it sure feels ugly.
